= Präsentation

== Einleitung

Ich begrüsse Sie herzlich zur Präsentation meiner Maturitätsarbeit.

Vor einigen Jahren habe ich einen Spruch an meine Schlafzimmerwand gemalt. Nicht nur, weil mein Zimmer umgestalten wollte, sondern weil mich, seit ich klein bin, verschiedene Unsicherheiten und Ängste plagen und einschränken.

== Fears

____

"Don't let your fears win"
____

Wie Sie alle selber aus eigener Erfahrung wissen, ist man als Jugendliche oder Teenagerin allen möglichen Ängsten ausgetzt.
Das geht von Fragen zur Identität, zum Aussehen, dazu, wie man wahrgenommen wird, wie man seinen eigenen Platz findet bis hin zu schulischer und sportlicher Leistung oder dazu die eigene Maturitätsarbeit zu präsentieren.

In meiner Arbeit habe ich eine dieser Ängste aufgegriffen, die mich seit langem sehr beschäftigt.
Es geht um das Aussehen und spezifisch um den Konflikt mit der eigenen Figur.

Die unmittelbarste Art, die eigene Figur zu sehen, ist es, sich vor einen Spiegel zu stellen und hineinzuschauen.

Physikalisch gesehen, reflektiert ein Spiegel nur das einfallende Licht und gibt genau das wieder, was vor ihm steht.
Man könnte also meinen, dass wenn man in den Spiegel hineinschaut, genau das sieht, wie einem die anderen sehen.
Tatsächlich unterscheiden sich Selbstwahrnehmung und Fremdwahrnehmung erheblich voneinander.

Mit meinem Stop-Motion Film "Spiegelszene" habe ich versucht diesen Konflikt visuell umzusetzen.

Das Ziel meiner Arbeit war es, mit einfachen gestalterischen Mitteln, einen etwas 2 Minuten langen Stop-Motion Film zu drehen.
Es war mein Ziel, den Zuschauer zum Nachdenken anzuregen, und ihm genügend Raum für eine eigene Interpretation zu lassen.

== Stop-Motion

Was aber ist ein Stop-Motion Film überhaupt?

Stop Motion ist eine Unterkategorie der Animationsfilme.
Animation ist jede Filmtechnik, die durch die Aneinnderreihung von unbewegten Bilder, die Illusion einer Bewegung erzeugt.
Diese Bilder können zum Beispiel gezeichnet oder programmiert sein.

Bei Stop Motion benutzt man Fotografien von unbewegten Motiven.
Bekannte Beispiele dafür sind etwa "Wallace & Grommit" oder "Pingu" und viele weitere.

== Preproduction

Bevor man einen Film drehen kann, muss man sich zuerst intensiv mit der Vorbereitung auseinandersetzen.
In der sogenannten Preproduction gibt es diese drei Hauptthemen.
Wie man sie gewichtet, kann jedoch auf Grund von persönlichen Erfahrungen variieren.

== Technik
Weil ich ohne Vorkenntnisse in dieses Gebiet eingetaucht bin, musste ich viel Zeit in die Technik investieren.
Ich musste ein passendes Animations- und Schnittprogramm finden und erlernen.

== Material

Das Material, der Szenenbau und die Ausarbeitung einer Geschichte sind auch essentiell.
Ich habe viel mit der Knetmasse Plastilin modelliert, um zu sehen was man alles mit Plastilin gestalten kann.
Ich habe verschiedene Formen und Figuren modelliert um ein Gefühl für das Material zu bekommen.

== Szenenbau

Nachdem ich das Material im Griff hatte, musste ich auch eine Szenenbild bauen, in dem meine Figuren spielen konnten.
Das Schlafzimmer ist auf das nötigste reduziert und bewusst ganz in Weiss gehalten um einen neutralen Hintergrund für die Geschichte zu haben.

== Geschichte

Die Geschichte selber ist natürlich sehr wichtig - man schaut sich ja einen eher wegen der Handlung als wegen der guten Produktion an.
Um die Geschichte von der Idee zu fertigem Film zu bringen, gibt es ein Hilfsmittel dass einem hilft, die Idee das erste Mal - ohne grossen Aufwand - zu visualiseren: Das Storyboard.

== Production

Beim Dreh gibt es neben dem offensichtlichem Produktionsschritt Filmen oder Fotografieren noch weitere Aspekte die man beachten muss.

Mit der Ausleuchtung einer Szene kann man weitere kreative Element in den Film einbauen.
Damit lassen sich zum Beispiel spezielle Stimmungen erzeugen.

Die Dreharbeiten alleine dauerten etwa 50 Stunden.
In dieser Zeit machte ich rund 3000 einzelne Fotos.

== Schnitt

Nun ging es darum die einzelnen Sequenzen zu einem gesamten Film zusammenzufügen.
Dafür habe ich im Schnittprogramm aus dem Rohmaterial den Film geschnitten.

== Ton

Die Zeit des Stummfilms ist schon lange vorüber und für einen Film ist der Ton beinahe wichtiger als das Bild.
Daher musste ich für alle Szenen passende Geräusche und atmosphärischen Hintergrund aufnehmen und im Schnitt hinzufügen.

== Farbkorrektur

Zu guter Letzt habe ich jede Sequenz farblich angepasst, um die eher kalten Originalbilder wärmer zu machen.
Hier sehen Sie den direkten Vergleich zwischen Original und der Farblich korrigierten Version.

== Film

Nach dieser technischen Einführung zeige ich Ihnen jetzt den fertigen Film

== Analyse

Die ursprüngliche Idee war es, die Handlung so zu gestalten, dass die blaue Figur in einer Art Teufelskreis gefangen ist und immer wieder das gleiche erlebt.
Es ist mir aber aufgefallen, dass das nicht besonders spannend ist.
Im zweiten Teil den Films habe ich deshalb eine zweite Figur eingeführt.
Damit wurde die Handlung komplexer und öffnete den Raum für Interpretation.
Ausserdem war es eine technische Herausforderung, denn die Animation von zwei Objekten ist deutlich anspruchsvoller als die eines einzelnen.


== Spontaneität

In diesem Film ist trotz der vielen Vorarbeit sehr viel spontan entstanden.
In vielen Szenen habe ich die Figuren intuitiv geformt und bewegt und dabei ist die Geschichte entstanden, die Sie jetzt gesehen haben.
Dadurch hat sich eine Geschichte entwickelt, die ich nicht vorher bis ins Detail geplant habe.
Das macht einerseits den Reiz dieses Films aus, andererseits ist es für mich sehr schwierig eine komplette Analyse zu machen.
Wenn Sie mich also fragen wollen, wieso die Figur dies oder das gemacht hat, werde ich oft sagen müssen, dass die Figuren das selbst bestimmt haben.
Ich habe ihnen nur den Raum und den Platz gegeben sich auszudrücken.
Und natürlich ist klar: Ich spreche unterbewusst durch die Figuren und habe damit intuitiv meine Gefühle gezeigt.
Ich glaube, dass ich damit der ursprünglichen Fragestellung meiner Arbeit Rechnung getragen habe: Wie kann ich Gefühle aufzeigen und Emotionen darstellen.

== Fazit

Meine Arbeit war komplex und sehr vielfältig. Das hat sie für mich sehr interessant gemacht. Dadurch konnte ich jedoch die verschiedenen Aspekte nicht vertieft erarbeiten. Nicht ohne Grund wirken bei einer Filmproduktion dutzende von Spezialisten mit. Trotzdem ist es mir gelungen die verschiedenen Dimensionen einzubringen und zu einem Endprodukt zusammen zu führen.
Der Hang zum Perfektionismus hat mich einige Stunden mehr gekostet und mich manchmal dazu verleitet mich in Details zu verlieren. Zudem war es schwierig für mich zu Beginn realistische Ziele zu setzen. Diese musste ich laufend anpassen.
Wenn ich wieder einmal so ein Projekt angehen würde, würde ich sehr viel mehr Zeit in die Planung investieren, um Unsicherheiten zu umgehen und mit mehr Zeit, hätte ich ein paar technische Unschönheiten behoben.




