= Die praktische Arbeit

Umgang mit Plastilin
Beleuchtung
Filmen



== Vorbereitung

== ?
Um mich an die Arbeit heranzutasten habe ich mich zuerst mit verschiedenen Modeliermassen auseinander gesetzt.
Fimo wurde mir in allen Bastelläden vorgeschlagen, obwohl sich später herausstellte, dass er sehr schnell brüchig und hart wird.
Dementsprechend nicht geeignet ist für meine Arbeit.
Plastilin erwies sich schlussendlich als das passendste Material.
Um mich daran zu gewöhnen habe ich eine Zeit lang oft damit modelliert und verschiedene Objekte nachgebildet, um zu sehen was man mit Plastilin anstellen kann.
Es wurde mir schnell klar, dass Plastilin für vieles sehr passend ist. Man kann sowohl einfarbige, als auch mehrfarbige beziehungsweise gemischte Objekte herstellen.
Von dick zu dünn ist ziemlich alles möglich.
Ein Nachteil hat das Material aber auch.
Es ist nicht sehr stabil, es reissen also dünne Teile eines Objektes ab oder knicken sehr schnell ein.
Die Standhaftigkeit eines Objektes ist sehr wichtig und somit einwenig einschränkend, denn man muss für die Standhaftigkeit immer einen eher dicken untersten Teil haben.

Nebenbei habe ich mich stetig mit theoretischen Grundlagen zum Filmen einer (((Animation))) auseinander gesetzt.
In YouTube Clips konnte ich mir die nötige Kenntnis für das Animieren von Knetfiguren aneignen. Kanäle wie "_Guldies_" oder "_Howcast_" halfen mir dabei sehr.

Um herauszufinden wie ich am besten meine Arbeit filmen kann, habe ich verschiedene Möglichkeiten ausprobiert und miteinander verglichen.
Die erste Technik, die ich angewendet habe war das heruntergeladene App "_StopMotion_" auf meinem iPhone, welches man auf ein extra für Smartphones konstruiertes Stativs montiert.
Dies erwies sich jedoch als nicht sehr geeignet, denn die Qualität des Filmes war nicht sehr überzeugend und unpraktisch zu bedienen, denn das iPhone auf dem Stativ war nicht sehr standhaft.
Weil man jedesmal beim Bedienen des Auslösers auf dem Bildschirm, das ganze Stativ ein wenig verschob und somit das Video wackelig wurde.

Nun habe ich auf dem Internet nach neuen Stop-Motion Programmen recherchiert. Erstmals wollte ich mir ein günstiges Programm suchen und so entschied ich mich für "_IStopMotion_".
Nachdem ich es gekauft habe, habe ich aber erst gemerkt, dass das Programm nicht mit Kameras zusammen funktioniert, deshalb musste ich auch bei diesem Programm wieder für mein Smartphone entscheiden.
"_IStopMotion_" war aber auch wieder eine grosse Enttäuschung, denn es stürzte ständig ab, durch das verlor man ständig die neu gefilmten Sachen und man konnte nicht manuell Scharfstellen.
Nach weiterem recherchieren bin ich dann auf das professionelle Animationsprogramm "[[[_Dragonframe_]]]" gestossen. Ich habe die Testversion auf meinen Computer geladen und eine dazu passende Kamera, eine "Nikon D700" von einer Familienfreundin organisiert. Mit der Testversion habe ich kurze Ausschnitte gefilmt und das komplizierte Programm versucht kennen zu lernen. Ich war mir ziemlich schnell klar, dass ich lieber Geld in ein gut funktionierendes Programm investieren möchte, als weitere Zeit zu verlieren. Deshalb kaufte ich mir die Software.

Während der Kameratechnischen Vorbereitung habe ich stetig in meinem Skizzenbuch neue Ideen für eine potentielle Handlung gesammelt und skizziert.

Zur Inspiration bin ich einen Abend zur Fantoche 2017 gegangen und habe mir "_Comfort Creatures_" angeschaut.
Bei diesen Stop-Motion Filmen wird viel mit der Sprache gearbeitet. Was sich nicht mit meiner Arbeit kreuzt, denn ich will eine Handlung ohne Worte aufzeigen können.

Eine ganze Weile habe ich verbracht mit dem Filmen von Testclips um das Programm "[[[Dragonframe]]]" kennen zu lernen und um meine Techniken zu optimieren, dass ich beim filmen der eigentlichen Arbeit draus komme und nicht zu viel unnötige Zeit aufwende.
Ausseredem habe ich mir zwei bewegliche Nachttischlampen und zwei LED Lichter zugelegt, um ein gutes Lichtverhältnis zu konstruieren.

Nach allen nötigen Grundausstattungsvorbereitungen habe ich mich für das filmen der Handlung in einem vorerst einzelnen Raum entschieden.
Ich habe einen Puppenhaus artigen Grundriss mit Boden aus Sperrholz konstruiert und zusammen gebaut.
Ausgestattet habe ich diesen mit selber gemachten Möbeln und Verzierungen.


== Die Drei-Punkt-Beleuchtung


== Schnitt und Ton

Nach dem fotografieren einer einzelnen Szene habe ich die Fotos als Video exportiert und in das Schnittprogramm "[[[Lightworks]]]" eingefügt.
Dort habe ich stetig die Videos hintereinander eingefügt und eine Grobversion des Filmes hergestellt.
Gleichzeitig habe ich mit einem "[[[Zoom H5]]]" Mikrofon Geräusche in meinem Haus aufgenommen, die passend zu den aufgenommenen Szenen waren.
Diese habe ich ebenfalls in "[[[Lightworks]]]" eingeführt.
