= Analyse

Bühnenbild:
Ich habe mich für den Bau eines Schlafzimmers entschieden, damit ich einen einheitlichen Raum zur Verfügung habe, der nicht nach jedem Filmprozess neu gestaltet oder umgebaut werden muss.
Das Puppenhaus ähnliche Schlafzimmer hat sich als sehr praktisch herausgestellt, denn ich konnte das ganze Zimmer verschieben und somit Perspektiven erzeugen, die nur mit der Verschiebung der Kamera nicht funktioniert hätten.
Die Farbe der Ausstattung habe ich ganz bewusst gesetzt.
Einerseits habe ich sie benutzt, um die Hauptfigur in den Fokus zu setzen.
Andererseits habe ich die Bedeutung der Farbe weiss recherchiert und war begeistert.
Wie die viversum Redaktion in ihrem Text zur Spiritualität beschreibt:

<"Sie steht für den Winter, für Eis und Schnee, sie gibt uns Kraft bei der Lösung unserer Probleme und wirkt unheimlich beruhigend: die Farbe Weiß.

Reinheit, Frische, Unschuld – die Farbe Weiß weckt viele Assoziationen in uns.

Doch Weiß ist noch so viel mehr als eine Farbe: In fernöstlichen Kulturen wie China oder Japan steht sie für Trauer und Tod, in der katholischen Kirche im Gegenteil für das Licht der Erleuchtung, das alles Sichtbare hervorbringt.

Sie festigt uns innerlich und befreit uns von störenden Gedanken."

Diese verschiedenen Deutungen konnte ich direkt mit meinem behandelten Inhalt assozieren.
Die Unschuld der eigenen Person, welche aber in tiefer Trauer steckt.
Und sich in ihrem weissen Raum von ihren störenden Gedanken und Problemen entfernt und sich befreit.

Ausserdem hat man auf dem Boden und den Wände nach einer gewissen zeit Rückstände der Knetfiguren und somit der Handlung feststellen können.
Mir hat diese automatisch passierende Geste sehr gut gefallen, denn für mich widerspiegelt das die Redewendung "Man hinterlässt überall seine Spuren".


Figur:

Die Knetmasse soll den unbestimmten Menschen darstellen.
Egal was für eine Hautfarbe, was für einen Körperbau oder welches Geschlecht, die Figur soll das "DU" aufzeigen.
Ob man sich auf diese Konfrontation einlassen will und sich mit dieser Figur oder Masse identifizieren will, wird einem selber überlassen.
Meine Figur soll einfach eine Fläche bieten, auf welcher sich der Zuschauer finden kann und sich seine persönliche Geschichte ausmalen kann.
Ausserdem wechselt die Figur ständig ihre Körperform und bleibt trotzdem unzufrieden.
Dies soll aufzeigen, dass nicht die Veränderung des eigentlichen Körperbilds die Zufriedenheit bewährt, sondern dass die Zufriedenheit im Kopf zuerst ermittelt werden muss.
Die Farbe Blau habe ich gewählt, weil sie für mich etwas kaltes und trauriges ausstrahlt, ausserdem kann sie nicht zu einer menschlichen Hautfarbe zugeteilt werden.
Deshalb entsteht ein, vom Menschen unabhängiges Individuum.
Die Figur ist ein von aussen beeinflusstes Wesen.
Gut erkennbar sind die Auswirkungen der Einflüsse, bei der Szene mit den Postern.
Nach dem Anschauen der "perfekten" Figuren fühlt sich die Hauptfigur zermürbt.
Diese Situation soll das wirkliche Leben widerspiegeln.
Wie in der Einleitung erklärt, befasse ich mich ständig mit diesem Thema und kenne diese Situation nur all zu gut.
Deshalb war es mir persönlich wichtig sie in meinem Film aufzuzeigen.


Zweite Figur:

Die Zweite Figur soll ein Vertreter der Unterstützung darstellen.
Sie soll die Hauptfigur dazu ansporen sich selber zu akzeptieren und zu realisieren, dass alles an ihr gut ist.
Ein wichtiger Aspekt für die Aussage der Handlung ist, als die beiden Figuren aufeinander treffen haben sie beide den selben Körperbau.
Beide erscheinen als eine Kugel.
Der Grundlegende Unterschied ist jedoch der Gemütszustand der beiden.
Die grüne Figur ist, trotz der gleichen Statur vollkommen zufrieden mit sich selbst und kann sich erfreut im Spiegel ansehen.
Die blaue Kugel ist alles andere als Zufrieden.
Die Umarmung der beiden soll der Auslöser der Besserung sein.
Es ist ein Austausch an Emotionen und Unterstützung.
Wenn man sich genau achtet, kann man erkennen, dass nach der Umarmung Rückstände der grünen Figur am Körper der blauen Figur hängen blieben.
Dies soll den Austausch deutlich machen und aufzeigen, dass sie jetzt nach der Umarmung und der weitergegebenen Vernunft, zufrieden sein kann und sich selber, so wie sie ist akzeptieren kann.
