= Schlusswort

== Diskussion

Um mein Produkt besser zu reflektieren, habe ich einen Ausschnitt aus einem anderen Stop-Motion Film analysiert und mit meiner Arbeit verglichen.
Adrian Flückiger's Film "What's Next" handelt von einem Jungen, der einen anderen jungen Bub an einen Stuhl fesselt, ihm den Mund verbindet und ein Erpresservideo machen will.
Am Schluss stellt sich heraus, dass er seinen kleinen Bruder gefesselt hat und in ihrem gemeinsamen Zimmer das Video dreht.
Adrian Flückiger schafft es in seinem kurzen Film eine Spannungskurve aufzubauen, die den Zuschauer in die Handlung hinein zieht, so dass man unbedingt das Ende der Geschichte wissen möchte.

Flückiger hat sein Bühnenbild ähnlich aufgebaut wie meines.
Das Schlafzimmer ist der Drehort und es erinnert an ein Puppenhaus.
Der grundlegende Unterschied bei der Innenausstattung, ist die Detaillierung.
Während ich davon abgesehen habe, hat er in seinem Film auf jedes kleinste Detail geachtet.
Das Schlafzimmer scheint fast identisch zu einem richtigen Schlafzimmer zu sein.
Im Verlauf seines Filmes zeigt er alle vier Wände des Zimmers, somit kann man sich das Zimmer als ganzes vorstellen.
In meinem Film gibt es die vierte Wand, die Perspektive der Kamera, nicht.
Die Materialien, die Flückiger in seinem Film braucht, sind fast die gleichen wie ich sie habe.
Er benutzt abgesehen von den Figuren gezeichnete Bilder die an der Wand des Raumes hängen, Drohbriefe, die er aus normalem Papier und aufgeklebten Papierfetzen herstellt.
Dies erinnert mich an die zwei gezeichneten Poster, die ich in meinem "Puppenhaus" aufgehängt habe.
Die Sturmmaske, die die Hauptperson trägt scheint von Hand gestrickt zu sein.
Die Decke, das Kissen und der Teppich des Zimmers, sind in meinem Film ebenfalls von Hand gestrickt.
Flückigers Figuren sind sehr interessant aufgebaut.
Es scheint als hätten sie einen beweglichen Körper, der mit Stoffkleidung bedeckt ist und einen festen Kopf und feste Hände, die am Körper angemacht sind.
Nur die Augen können sich bewegen und dienen somit als einzige Möglichkeit für Gestiken.
Um Gefühle und Ausdrücke der Figuren zu zeigen, arbeitet Flückiger intestiv mit der Vertonung des Filmes.
Die Hintergrundmusik verleiht der Handlung eine unbeschreibliche Anspannung, ausserdem schafft er es mit Geräuschen die Emotionen der Figuren dem Zuschauer zu vermitteln.
Ausschlag gebend für die Dramaturgie des Kurzfilmes ist ausserdem die Beleuchtung.
Mit Hilfe der Insenzierung von Schatten, schafft es Flückiger die Situation viel intensiver zu gestalten.
Kleine Objekte wirken durch die klaren Schatten riesig.
Ausserdem werden Bewegungen und Handlungen mit Hilfe des Schattens gezeigt.
Beispielsweise wo die Kamera nur den Schlitz unter der Türe filmt und man den Schatten einer Person erkennen kann.
Interessant ist auch der Unterschied der Beleuchtung der Figuren.
Es scheint als hätte Flückiger gewollt ein einzelnes Licht auf das Opfer geschienen, damit diese im Fokus steht, während der Täter durch das eher dunkel wirkt.
Flückiger hat nachträglich Effekte mit dem Computer hinzugefügt, die die Handlung der Geschichte klarer machen.
Geschickterweise hat er eine Kamera eingebaut, die zur Geschichte gehört.
Somit kann er mit einer allwissenden, beobachtenden Kamera filmen und die Hauptperson der Geschichte filmt mit einer anderen Kamera.
Die Nahaufnahmen des Opfers sind somit durch die "Handlungskamera" legitimiert und logisch eingesetzt.
Sie bietet ausserdem Hilfe für das Verständnis des Betrachters.

Flückiger hat mit Hilfe seines Teams einen sehr authentischen, lebhaften Stop-Motion Film kreiert, der durch die Abwechslung zwischen Anspannung und Humor eine gute Unterhaltung bietet. 

== Reflexion

Das zu Beginn gestellte Ziel war es, einen rund 2 Minuten langen Kurzfilm in _Stop-Motion_ Technik zu drehen, der den Zuschauer zum Nachdenken anregen soll.
Ich habe ungefähr 3000 einzelne Bilder fotografiert, die nacheinander abgespielt, einen etwa 4 Minuten langen Film ergeben.
Mein Produktionsziel habe ich somit erreicht.
Zusätzlich habe ich mir verschiedenste Techniken, die ich für die Produktion eines Stop-Motion Film brauchte, selber beigebracht.
Anhand von simpeln Figuren habe ich versucht, menschliche Emotionen und Ausdrücken wiederzugeben, die dem Zuschauer bekannt vorkommen sollen.
Der Zuschauer sollte damit die Geschichte anhand von diesen Eindrücken selber erarbeiten.
Anfangs wollte ich eine Handlung zeigen, die kein "Happy End" hat und sich als endlose Schlaufe abspielen lässt.
Im Laufe des Projekts habe ich mich aber umentschieden, zu Gunsten eines interessanteren Spannungsbogen, und habe somit mein ursprüngliches Ziel der Handlung verworfen.
Durch die Reaktionen von Bekannten und Freunden, die meinen Film angeschaut haben, kann ich sagen, dass die Handlung klar erkannt wurde, ohne dass ich sie vorher erzählt oder erklärt habe.

Im Verlauf meiner Arbeit hatte ich viele zusätzliche Ideen und Vorstellungen.
Ich habe mir einen interessanten, abwechslungsreichen Kurzfilm vorgestellt, mit verschiedenen Handlungssträngen.
Doch es zeigte sich, dass meine Vorstellungen weit über meiner zeitlichen Kapazität waren und im Rahmen dieser Maturitätsarbeit sich nicht realisieren liessen.
Ich habe mich darauf beschränkt, den Film in einem einzigen Raum und einer einzigen Lichteinstellung spielen zu lassen.

Was mir ebenfalls im Weg stand, war mein Hang zum Perfektionismus.
Ich habe mich oft in der Gestaltung von Details und Feinschliffen in der Produktion verloren, was mich wertvolle Zeit kostete.
Im Rückblick wäre es besser gewesen, hätte ich mich auf das Wesentliche fokussiert.
So hätte ich mehr Zeit für die Auseinandersetzung mit dem Material investieren können, was sich im Film mit verschiedenen spielerischen Elementen manifestiert hätte.

== Ausblick

Am Ende jedes Projektes blickt man zurück und denkt sich, dass noch vieles hätte gemacht und erweitert werden können.
Ich habe mich im Verlauf meiner Arbeit bewusst auf das Erstellen eines kurzen Filmes beschränkt, der nur ein Bühnenbild und relativ einfache Figuren braucht, um am Ende ein gutes, in sich abgeschlossenes Projekt zu präsentieren.

Gerne hätte ich weitere Elemente hinzugefügt.

Das könnte auf verschiedenen Ebenen geschehen.

Das bestehende Film- und Tonmaterial liesse sich zu einer neuen Geschichte zusammensetzen, indem man im Schnittprogramm einen anderen Ablauf erstellt.
Das Schnittprogramm selber bietet viele weitere Möglichkeiten mit dem Bildmaterial umzugehen und es zu gestalten (z.B. durch Verfremdung und Veränderung der Farben, etc.).
Durch das Verwenden von diesen Techniken könnten weitere thematische Aspekte visualisiert werden.
Zum Beispiel liesse sich eine hoffnungsfrohe oder hoffnungslose Stimmung der Hauptfigur durch entsprechende Lichtgestaltung zeigen.

Das Element Ton ist ein weiteres Element, mit dem sich der Film verändern lässt.
Ich habe bewusst nur Geräusche und keine Sprache verwendet.
Wenn man den Figuren eine Sprache verleihen würde, könnte das Erzählen der Geschichte stärker definiert werden. Dafür würde man dem Publikum den Interpretationsspielraum einschränken.

Im Rahmen der bestehenden Szenerie kann man das besprochene Thema erweitern und weitere Dimensionen beleuchten.
Zum Bespiel könnte man das Thema in Richtung "psychische Krankheitsbilder", Auswirkung von gruppendynamischen Prozessen und die gesellschaftliche Relevanz des Hauptthemas ausweiten.
Um die Geschichte zu vertiefen, müssten weitere Figuren und weitere Schauplätze eingefügt werden.
Aufgrund meiner Erfahrung weiss ich, dass ich ca 90 Minuten Arbeit brauche um 10 Sekunden Rohfilm zu filmen.
Viel mehr Aufwand ist aber das Entwickeln der Idee, das schneiden und das Vertonen.
Zusätzlich zum Aufwand, den ich oben beschrieben habe, kommt das Bauen der Kulisse.
Je nach Komplexität der Szenerie entstehen hier mehrere Tage Aufwand.

Falls man die Zeit findet, wäre es sicherlich spannend sich in die verschiedenen Richtungen zu vertiefen.
