= Schlusswort

== Diskussion



== Reflexion

Das zu Beginn gestellte Ziel war es, einen _Stop-Motion_ etwa 2 Minuten langen Kurzfilm zu drehen, der den Zuschauer zum Nachdenken anspornen soll.
Ich habe ungefähr 3000 einzelne Bilder fotografiert, die nacheinander abgespielt einen etwa 4 Minuten langen Film ergeben.
Mein anfängliches Ziel ist somit erreicht.
Ausserdem habe ich mir verschiedenste Techniken, die ich für die Produktion eines Stop-Motion Film brauchte, selber beigebracht.
Anhand von simpeln Figuren habe ich versucht menschliche Emotionen und Ausdrücke wiederzugeben, die dem Zuschauer bekannt vorkommen sollen und er die Geschichte anhand von diesen Eindrücken selber erarbeiten soll.
Anfangs wollte ich eine Handlung aufzeigen, die kein "Happy End" hat und sich als endlose Schlaufe der Handlung abspielen lassen könnte.
Schlussendlich habe ich mich aber umentschieden und konnte somit mein eigentliches Ziel der Handlung nicht erfüllen. 
Durch die Reaktionen von Bekannten, die meinen Film angeschaut haben, kann ich sagen, dass die Handlung klar erkannt wurde, ohne dass ich sie informiert habe.
Im Verlauf meiner Arbeit hatte ich manche Ideen und Vorstellungen.
Ich habe mir einen interessanten, abwechslungsreichen Kurzfilm vorgestellt, mit verschiedenen Handlungssträngen.
Doch es erwies sich, dass meine Vorstellungen weit über den Möglichkeiten waren und meinem möglichem Zeitaufwand nicht entsprachen.
Deshalb habe ich mich schlussendlich auf einen Raum eingeschränkt.
Rückblickend hätte ich von Anfang an, mich vom Perfektionismus müssen entfernen, damit ich nicht wertvolle Zeit an kleinen Details verliere.


== Ausblick

Wie jeder Arbeitsprozess, könnte auch dieser noch weitergeführt werden.
Ich habe mich im Verlauf meiner Arbeit bewusst auf einen kurzen Film eingegrenzt, der nur ein Bühnenbild braucht, damit ich meine Ziele realisieren konnte und nun ein anständiges, vollendetes Produkt präsentieren kann.
Trotzdem könnte man meinem Projekt weitere Elemente hinzufügen.

Man könnte einerseits verschiedene weitere Szenen mit anderen Schauplätzen filmen und hinzufügen, dies würde jedoch vermutlich zu einer Veränderung der Handlung führen.
Wenn man sich nicht auf die jetzige Handlung beschränkt, könnte man das angesprochene Thema ausgiebig erweitern.
Andererseits könnte man das jetzige Produkt weiter angehen und ausbauen.
Das Schnittprogramm bietet sehr viele Möglichkeiten, um das vorhandene Film und Ton Material zu bearbeiten.
Man kann durch das unterschiedliche aneinanderfügen von Abläufen, völlig verschiedene Geschichten erzählen und somit andere Aussagen machen.
In meiner Arbeit habe ich mich auf Geräusche eingeschränkt und habe die Verwendung von Sprache ausgeschlossen.
Durch das Verbalisieren einer Handlung kann man viele weitere Türen der Möglichkeiten öffnen.

Es wäre spannend in Zukunft eine Weiterführung dieser Arbeit in Betracht zu nehmen.
Eine andere Möglichkeit währe es, die jetzige Arbeit an ein Publikum zu richten.
Ich könnte mir vorstellen die nun vorliegende Arbeit einem jungen, unsicheren Publikum vorzustellen, welches meine Arbeit als Gelegenheit, um ihre Gefühle, Gedanken oder Probleme zu reflektieren, nutzen kann und sich inspirieren kann.
