= Schlusswort

== Diskussion



== Reflexion
- Wie kann ich an Hand von einfachen Figuren Emotionen / Verhalten / Gedanken und Botschaften ausdrücken?
- Was genau ist "(((Claymation)))" und welche gestalterischen Methoden lassen sich dabei anwenden?

Im Verlauf meiner Arbeit habe ich viel Unbekanntes gelernt.
Ich habe ge

== Ausblick

Wie jeder Arbeitsprozess, könnte auch dieser noch weitergeführt werden.
Ich habe mich im Verlauf meiner Arbeit bewusst auf einen kurzen Film eingegrenzt, der nur ein Bühnenbild braucht, damit ich meine Ziele realisieren konnte und nun ein anständiges, vollendetes Produkt präsentieren kann.
Trotzdem könnte man meinem Projekt weitere Elemente hinzufügen.

Man könnte einerseits verschiedene weitere Szenen mit anderen Schauplätzen filmen und hinzufügen, dies würde jedoch vermutlich zu einer Veränderung der Handlung führen.
Wenn man sich nicht auf die jetzige Handlung beschränkt, könnte man das angesprochene Thema ausgiebig erweitern.
Andererseits könnte man das jetzige Produkt weiter angehen und ausbauen.
Das Schnittprogramm bietet sehr viele Möglichkeiten, um das vorhandene Film und Ton Material zu bearbeiten.
Man kann durch das unterschiedliche aneinanderfügen von Abläufen, völlig verschiedene Geschichten erzählen und somit andere Aussagen machen.
In meiner Arbeit habe ich mich auf Geräusche eingeschränkt und habe die Verwendung von Sprache ausgeschlossen.
Durch das Verbalisieren einer Handlung kann man viele weitere Türen der Möglichkeiten öffnen.

Es wäre spannend in Zukunft eine Weiterführung dieser Arbeit in Betracht zu nehmen.
Eine andere Möglichkeit währe es, die jetzige Arbeit an ein Publikum zu richten.
Ich könnte mir vorstellen die nun vorliegende Arbeit einem jungen, unsicheren Publikum vorzustellen, welches meine Arbeit als Gelegenheit, um ihre Gefühle, Gedanken oder Probleme zu reflektieren, nutzen kann und sich inspirieren kann. 
